In [1]:

import numpy as np
import time

In [ ]:
#numpy 
a=np.arange(10000000)
b=np.arange(10000000,20000000)
start=time.time()
c=a+b
print(time.time()-start)

#list 
l1=[x for x in range(10000000)]
l2=[x for x in range(10000000)]
c=[]
start=time.time()
for i in range(10000000):
    c.append(l1[i]+l2[i])
print(time.time()-start)

0.04514026641845703


In [4]:
#list vs numpy
#speed -  numpy takes much lesser time as comp to list

#numpy array has fixed size and non-referential 


#memory
a=[i for i in range(10000000)]
import sys 
sys.getsizeof(a)

89095160

In [5]:
import numpy as np
a=np.arange(10000000)
sys.getsizeof(a)

80000112

In [6]:
# convenience of working in numpy 

#Advaned Indexing 
a=np.random.randint(1,100,24).reshape(6,4)
a

array([[82, 85, 95, 64],
       [17, 76, 74, 45],
       [86,  8, 13, 59],
       [71,  4, 44, 16],
       [22,  3,  9, 73],
       [70, 56,  7, 35]], dtype=int32)

In [ ]:
#Fancy Indexing 

# extract (1,3,4)th row 
indices=[1,3,4]
a[indices]

a[:,[0,2,3
     ]]



array([[82, 95, 64],
       [17, 74, 45],
       [86, 13, 59],
       [71, 44, 16],
       [22,  9, 73],
       [70,  7, 35]], dtype=int32)

In [15]:
#Boolean Indexing - to extract indices that are logially extracted 

#find all numbers>50
a[a>50]
#find all even numbers 
a[a%2==0]

# find all numbers>50 and even 
a[(a>50) & (a%2==0 )]

#find all



array([82, 64, 76, 74, 86, 70, 56], dtype=int32)

In [18]:
#BroadCasting desc how numpy treats array with diff shapes during arithmetic operations 
# The smaller array is "broadcast" accross larger array so that they have compatible shapes
a=np.arange(6).reshape(2,3)
b=np.arange(3).reshape(1,3)
a+b

array([[0, 2, 4],
       [3, 5, 7]])

BROADCASTING RULES 
r1 -> MAKE THE TWO ARRAYS HAVE THE SAME DIMENSIONS(if the no of dimensions r diff, add new dimensions with size 1 to the head of the arr with the samller dimension )

r2-> MAKE EACH DIMENSION OF THE ARR THE SAME SIZE(if the sizes of each dimension of the two arr don't match , dimensions with size 1 r stretched to the size of the other arr , IF there is a dimension whose size!=1 in either of the two arr , it can't be broadcasted and en err is raised )

In [3]:
import numpy as np
a=np.arange(12).reshape(3,4)
b=np.arange(6).reshape(3,2)

Mathematical Formula

In [ ]:
#SIGMOID - 1/(1+exp(-x))

import math;
def sigmoid(x):
    return 1/(1+np.exp(-x))
x=np.arange(10)
sigmoid(x)


#MEAN SQUARED ERROR 

actual=np.random.randint(1,50.25)
predicted=np.random.randint(1,50,25)

def meanSquaredErr(actual,predicted):
    return np.mean((actual-predicted)**2)
meanSquaredErr(actual,predicted)



#CATEGORICAL CROSS ENTROPY 




np.float64(195.24)

WORKING WITH MISSING VALUES -> np.nan 

In [18]:
a=np.array([1,2,3,4,5,np.nan,6])

a[~np.isnan(a)]

array([1., 2., 3., 4., 5., 6.])

AttributeError: 'numpy.ndarray' object has no attribute 'isnull'