In [ ]:
import numpy as np
# it is a fundamental package for scientific computing in python . 
# It is a py lib that provides multi dim obj various derived objets(such as masked arrays and matrices) and an asortment of routines for fast operations on arrays including mathematical , logical , shape manip , sorting ,selecting ,I/O, etc 
#numpy arrays vs other seq
#-> np.array is of fixed size , changing its size will create a new array and del the org
#-> its eles r req to be of the same data type
#-> facilitates adv math oper . more efficiently 

  

In [2]:
L=[1,2,3,5]
arr=np.array(L)

type(arr)

numpy.ndarray

In [4]:
# 2D , 3D ARRAYS
L=[[1,2,3],[3,4,5]]
brr=np.array(L)
type(brr)

numpy.ndarray

In [5]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [11]:
#np.arange , a range
np.arange(1,100,5)

#with reshape
np.arange(1,7).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# np.ones and np.zeros-> used to init 
np.ones(3,4)

In [12]:
# np.random.random()
np.random.random((2,3))

array([[0.93939077, 0.51448416, 0.99691791],
       [0.41755071, 0.64764487, 0.38364503]])

In [14]:
#np.linspace -> from , to , count -> generates count number of points between start and end 
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [15]:
#np.identity 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

ARRAY ATTRIBUTES

In [ ]:
a1=np.arange(10) # array
a2=np.arange(12,dtype=float).reshape(3,4) #matrix
a3=np.arange(8).reshape(2,2,2) #tensor



In [26]:
#ndim 
a1.ndim
a2.ndim
a3.ndim
#shape
a3.shape # output (kitne arrays ,(row,col))


#size
a3.size

#itemsize , size of each item in memory
a3.itemsize

#dtype
a3.dtype

dtype('int64')

CHANGING DATATYPE

In [27]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

ARRAY OPERATIONS

In [28]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)


In [32]:
#scalar operations 



#arithmetic
a1=a1*2
print(a1)

[[ 48  54  60  66]
 [ 72  78  84  90]
 [ 96 102 108 114]]
