In [ ]:
import numpy as np
# it is a fundamental package for scientific computing in python . 
# It is a py lib that provides multi dim obj various derived objets(such as masked arrays and matrices) and an asortment of routines for fast operations on arrays including mathematical , logical , shape manip , sorting ,selecting ,I/O, etc 
#numpy arrays vs other seq
#-> np.array is of fixed size , changing its size will create a new array and del the org
#-> its eles r req to be of the same data type
#-> facilitates adv math oper . more efficiently 

  

In [2]:
L=[1,2,3,5]
arr=np.array(L)

type(arr)

numpy.ndarray

In [4]:
# 2D , 3D ARRAYS
L=[[1,2,3],[3,4,5]]
brr=np.array(L)
type(brr)

numpy.ndarray

In [5]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [11]:
#np.arange , a range
np.arange(1,100,5)

#with reshape
np.arange(1,7).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# np.ones and np.zeros-> used to init 
np.ones(3,4)

In [12]:
# np.random.random()
np.random.random((2,3))

array([[0.93939077, 0.51448416, 0.99691791],
       [0.41755071, 0.64764487, 0.38364503]])

In [14]:
#np.linspace -> from , to , count -> generates count number of points between start and end 
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [15]:
#np.identity 
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

ARRAY ATTRIBUTES

In [ ]:
a1=np.arange(10) # array
a2=np.arange(12,dtype=float).reshape(3,4) #matrix
a3=np.arange(8).reshape(2,2,2) #tensor



In [26]:
#ndim 
a1.ndim
a2.ndim
a3.ndim
#shape
a3.shape # output (kitne arrays ,(row,col))


#size
a3.size

#itemsize , size of each item in memory
a3.itemsize

#dtype
a3.dtype

dtype('int64')

CHANGING DATATYPE

In [27]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

ARRAY OPERATIONS

In [28]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)


In [ ]:
#scalar operations 



#arithmetic
a1=a1*2
print(a1)


[[192 216 240 264]
 [288 312 336 360]
 [384 408 432 456]]


array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [35]:
#vector operations

#arithmetic
a1+a2

array([[204, 229, 254, 279],
       [304, 329, 354, 379],
       [404, 429, 454, 479]])

ARRAY FUNCTIONS

In [39]:
a1=np.random.random((3,3))
a1=np.round(a1*100)
a1

array([[14.,  7., 91.],
       [26., 33., 59.],
       [21.,  9., 82.]])

In [ ]:
#max , min ,sum ,product
np.max(a1)
np.min(a1)
np.sum(a1)

# find minimum of each row
np.min(a1,axis=0) # 0 is column and 1 is row

array([14.,  7., 59.])

In [43]:
# mean , median , std , var
np.mean(a1,axis=0)
np.median(a1,axis=0)
np.std(a1,axis=0)

array([ 4.92160769, 11.81336343, 13.47425529])

In [44]:
#trigonometric func
np.sin(a1)

array([[0.99060736, 0.6569866 , 0.10598751],
       [0.76255845, 0.99991186, 0.63673801],
       [0.83665564, 0.41211849, 0.31322878]])

In [46]:
#dot product
a2=np.arange(12).reshape(3,4)
a3=np.arange(12,24).reshape(4,3)
np.dot(a3,a2)

array([[164, 203, 242, 281],
       [200, 248, 296, 344],
       [236, 293, 350, 407],
       [272, 338, 404, 470]])

In [47]:
#log and expo
np.log(a1)
np.exp(a1)

array([[1.20260428e+06, 1.09663316e+03, 3.31740010e+39],
       [1.95729609e+11, 2.14643580e+14, 4.20121040e+25],
       [1.31881573e+09, 8.10308393e+03, 4.09399696e+35]])

In [ ]:
# round floor ceil
np.round(np.random.random((2,3))*100)
np.floor(np.random.random((2,3))*100)
np.ceil(np.random.random((2,3))*100)


array([[ 5., 44., 93.],
       [80., 97., 63.]])

In [50]:
#indexing and slicing
a1=np.arange(10)
a2=np.arange(12).reshape(3,4)
a3=np.arange(8).reshape(2,2,2)

In [57]:
a2[1,2] # accessing the element in 2-D array
a2[1,0]


# accessing the 3-D Array
a3[1,0,1] # array number , row , col
a3
a3[0,0,0]

np.int64(0)

In [ ]:
# slicing - can get multiples item together 
a1[2:5] 


array([2, 3, 4])

In [60]:
a2[0,:]

array([0, 1, 2, 3])

In [61]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[::2,::3] 

array([[ 0,  3],
       [ 8, 11]])

In [63]:
a3[1]

array([[4, 5],
       [6, 7]])

ITERATING

In [65]:
for i in a1:
    print(i,end=' ')

0 1 2 3 4 5 6 7 8 9 

In [ ]:
for arr in a2:
    for ele in arr : 
        print(ele,end=' ')
    print('\n')

0 1 2 3 4 5 6 7 8 9 10 11 

In [69]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7


In [70]:
#Reshaping - reshape , transpose , ravel
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
a2.ravel() # flatten mulit D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

STACKING

In [72]:
# if without printing you get to see the result , then that operation just return the array and donot permanently changes the original array 

In [ ]:
#horizontal stacking 

a1=np.random.random((5,10))
a2=np.arange(51,101).reshape((5,10))

np.hstack((a1,a2))

#vertical stacking
np.vstack((a1,a2))


SPLITTING

In [83]:
#HSPLIT 

np.hsplit(a1,2)

#VSPLIT

[array([[0.83792671, 0.65021258, 0.57152535, 0.53171696, 0.867076  ],
        [0.87297266, 0.22508385, 0.90475324, 0.50426049, 0.87121147],
        [0.57528183, 0.93531944, 0.42793213, 0.89711871, 0.39683573],
        [0.00747397, 0.47078727, 0.98682947, 0.91708624, 0.10475671],
        [0.79157835, 0.12805675, 0.6853947 , 0.74099541, 0.34832839]]),
 array([[0.06942526, 0.36009096, 0.93706913, 0.59018243, 0.70376876],
        [0.42390061, 0.22248312, 0.40175622, 0.21115058, 0.10783918],
        [0.28214323, 0.79322331, 0.90140673, 0.12067095, 0.70972765],
        [0.50871787, 0.11939725, 0.4521195 , 0.12417022, 0.63224845],
        [0.22259835, 0.52328835, 0.71074869, 0.8711084 , 0.40747163]])]